//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GitLogger.AzureFunctions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class html {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal html() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GitLogger.AzureFunctions.html", typeof(html).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;GitLogger Error Page&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;&lt;a href=&quot;https://github.com/mishra14/GitLogger&quot;&gt;GitLogger&lt;/a&gt;&lt;/h1&gt;
        ///
        ///    Error while generating the git logs.
        ///
        ///    &lt;form action=&quot;/api/request&quot;&gt;
        ///        &lt;input type=&quot;submit&quot; value=&quot;Return&quot;&gt;&lt;br&gt;&lt;br&gt;
        ///    &lt;/form&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;GitLogger Invalid Input Page&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;&lt;a href=&quot;https://github.com/mishra14/GitLogger&quot;&gt;GitLogger&lt;/a&gt;&lt;/h1&gt;
        ///
        ///    Invalid request. Please provide the following inputs: &lt;br/&gt;&lt;br/&gt;
        ///    
        ///    Start Commit SHA: The commit sha for the starting commit to be used while generating logs.&lt;br /&gt;&lt;br /&gt;
        ///
        ///    Code Repository: Github code repository name in the format - Owner [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string inputError {
            get {
                return ResourceManager.GetString("inputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;GitLogger Request Page&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;&lt;a href=&quot;https://github.com/mishra14/GitLogger&quot;&gt;GitLogger&lt;/a&gt;&lt;/h1&gt;
        ///    &lt;form action=&quot;/api/request&quot;&gt;
        ///        Start Commit SHA: &lt;input type=&quot;text&quot; name=&quot;startCommitSha&quot;&gt;&lt;br&gt;&lt;br&gt;
        ///        Code Repository Name: &lt;input type=&quot;text&quot; name=&quot;codeRepoName&quot; value=&quot;NuGet/NuGet.Client&quot;&gt;&lt;br&gt;&lt;br&gt;
        ///        Issue Repository Name: &lt;input type=&quot;tex [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string request {
            get {
                return ResourceManager.GetString("request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;GitLogger Response Page&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;&lt;a href=&quot;https://github.com/mishra14/GitLogger&quot;&gt;GitLogger&lt;/a&gt;&lt;/h1&gt;
        ///
        ///    Successfully generated git logs. The file is attached with the response.
        ///
        ///    &lt;form action=&quot;/api/request&quot;&gt;
        ///        &lt;input type=&quot;submit&quot; value=&quot;Return&quot;&gt;&lt;br&gt;&lt;br&gt;
        ///    &lt;/form&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string response {
            get {
                return ResourceManager.GetString("response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///
        ///&lt;html lang=&quot;en&quot; xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;GitLogger Unsupported Page&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;h1&gt;&lt;a href=&quot;https://github.com/mishra14/GitLogger&quot;&gt;GitLogger&lt;/a&gt;&lt;/h1&gt;
        ///
        ///    Invalid request. This azure function only supports GET requests.
        ///
        ///    &lt;form action=&quot;/api/request&quot;&gt;
        ///        &lt;input type=&quot;submit&quot; value=&quot;Return&quot;&gt;&lt;br&gt;&lt;br&gt;
        ///    &lt;/form&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string unsupported {
            get {
                return ResourceManager.GetString("unsupported", resourceCulture);
            }
        }
    }
}
